### ISSUE TITLE
please release to npm and or bower

### ISSUE THREAD

**Issue by nmccready** [consbio/Leaflet.ZoomBox#1]
Also please add a version via tagging.

**Comment by brendan-ward** [comment]
@nmccready do you have a preference between the two?

**Comment by nmccready** [comment]
Bower for now.

@nmccready https://github.com/nmccready do you have a preference between
the two?

**Comment by brendan-ward** [comment]
@nmccready Thanks for the prompt to get this done.

`bower install Leaflet.ZoomBox`

`npm install leaflet-zoombox`

**Comment by nmccready** [comment]
Thanks for the quick fix
