### ISSUE TITLE
Rectangle stays visible when right click

### ISSUE THREAD

**Issue by rsofista** [consbio/Leaflet.ZoomBox#11]
When you left-click and drag, drawing the rectangle, and you right-click before you release the left button the rectangle doesn't disappear.

**Comment by rsofista** [comment]
If you start dragging with the right mouse button and you keep clicking with the right mouse button you create multiple rectangles.

**Comment by brendan-ward** [comment]
@rsofista thanks for reporting this, I hadn't experimented with interactions with other mouse buttons.  I'll have to see if there is something in Leaflet we can hook into to clear the state or disable right click when drawing the zoom box (the latter might  be easier).
