### ISSUE TITLE
R implementation

### ISSUE THREAD

**Issue by jamesdalg** [consbio/Leaflet.ZoomBox#18]
This seems like an amazing tool, but I'm using the the R version of leaflet. Is there some way to make your plugin work for that platform? I imagine that using htmlwidgets::onRender() could be used to get the  CSS and javascript in the right places, but I can't quite get it to work. I have the contents of the package in the current working directory, but nothing quite seems to work.

m <- leaflet() %>%
  addTiles() %>% addMouseCoordinates() %>% addLayersControl() %>%
addMeasure()  %>%
  addMiniMap( toggleDisplay = TRUE,
              position = "topright") %>% addDrawToolbar() %>% addFullscreenControl() %>% # htmlwidgets::onRender(paste0("
<link rel=\"stylesheet\" href=\"L.Control.ZoomBox.css\" />
<script src=\"L.Control.ZoomBox.min.js\"></script>
var options = {
    modal: true,
    title: 'Box area zoom'
};
var control = L.control.zoomBox(options);
map.addControl(control);"))

**Comment by brendan-ward** [comment]
Hi @jamesdalg - unfortunately we are not able to support the R version of Leaflet, as we do not use that.  I would be willing to consider a small Pull Request to add support provided it doesn't complicate the overall logic of this tool.  If there is a specific change you can point us to that wold fix this, it would be helpful.

This tool hooks into the underlying zoom box functionality of the Leaflet map, and accesses it from this control.  Most of the magic is [here](https://github.com/consbio/Leaflet.ZoomBox/blob/master/L.Control.ZoomBox.js#L30-L39).

It could be that Leaflet for R does not provide the same bindings for us to hook into.

I'm unfamiliar with using plugins with Leaflet for R, so unfortunately I'm not able to provide further guidance.
